### ISSUE TITLE
i get this error

### ISSUE THREAD

**Issue by itsreyi** [mat-1/matscan#1]
Compiling mongodb v2.6.1
   Compiling matscan v0.1.0 (C:\Users\patia\Downloads\matscan-master\matscan-master)
error[E0433]: failed to resolve: could not find `unix` in `os`
 --> src\net\raw_sockets.rs:3:14
  |
3 | use std::os::unix::io::{AsRawFd, RawFd};
  |              ^^^^ could not find `unix` in `os`

error[E0425]: cannot find value `IF_NAMESIZE` in crate `libc`
 --> src\net\raw_sockets.rs:9:36
  |
9 |     ifr_name: [libc::c_char; libc::IF_NAMESIZE],
  |                                    ^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `IF_NAMESIZE` in crate `libc`
  --> src\net\raw_sockets.rs:15:29
   |
15 |         ifr_name: [0; libc::IF_NAMESIZE],
   |                             ^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find function `ioctl` in crate `libc`
  --> src\net\raw_sockets.rs:30:25
   |
30 |         let res = libc::ioctl(lower, cmd as _, ifreq as *mut ifreq);
   |                         ^^^^^ not found in `libc`

error[E0425]: cannot find value `AF_PACKET` in crate `libc`
  --> src\net\raw_sockets.rs:63:23
   |
63 |                 libc::AF_PACKET,
   |                       ^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `SOCK_RAW` in crate `libc`
  --> src\net\raw_sockets.rs:64:23
   |
64 |                 libc::SOCK_RAW | libc::SOCK_NONBLOCK,
   |                       ^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `SOCK_NONBLOCK` in crate `libc`
  --> src\net\raw_sockets.rs:64:40
   |
64 |                 libc::SOCK_RAW | libc::SOCK_NONBLOCK,
   |                                        ^^^^^^^^^^^^^ not found in `libc`

error[E0422]: cannot find struct, variant or union type `sockaddr_ll` in crate `libc`
   --> src\net\raw_sockets.rs:88:30
    |
88  |           let sockaddr = libc::sockaddr_ll {
    |                                ^^^^^^^^^^^ help: a struct with a similar name exists: `sockaddr`
    |
   ::: C:\Users\patia\.cargo\registry\src\index.crates.io-6f17d22bba15001f\libc-0.2.147\src\windows\mod.rs:55:1
    |
55  | / s! {
56  | |     // note this is the struct called stat64 in Windows. Not stat, nor stati64.
57  | |     pub struct stat {
58  | |         pub st_dev: dev_t,
...   |
102 | |     }
103 | | }
    | |_- similarly named struct `sockaddr` defined here

error[E0425]: cannot find value `AF_PACKET` in crate `libc`
  --> src\net\raw_sockets.rs:89:31
   |
89 |             sll_family: libc::AF_PACKET as u16,
   |                               ^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `sockaddr_ll` in crate `libc`
   --> src\net\raw_sockets.rs:101:43
    |
101 |                   &sockaddr as *const libc::sockaddr_ll as *const libc::sockaddr,
    |                                             ^^^^^^^^^^^ help: a struct with a similar name exists: `sockaddr`
    |
   ::: C:\Users\patia\.cargo\registry\src\index.crates.io-6f17d22bba15001f\libc-0.2.147\src\windows\mod.rs:55:1
    |
55  | / s! {
56  | |     // note this is the struct called stat64 in Windows. Not stat, nor stati64.
57  | |     pub struct stat {
58  | |         pub st_dev: dev_t,
...   |
102 | |     }
103 | | }
    | |_- similarly named struct `sockaddr` defined here

error[E0412]: cannot find type `sockaddr_ll` in crate `libc`
   --> src\net\raw_sockets.rs:102:38
    |
102 |                   mem::size_of::<libc::sockaddr_ll>() as libc::socklen_t,
    |                                        ^^^^^^^^^^^ help: a struct with a similar name exists: `sockaddr`
    |
   ::: C:\Users\patia\.cargo\registry\src\index.crates.io-6f17d22bba15001f\libc-0.2.147\src\windows\mod.rs:55:1
    |
55  | / s! {
56  | |     // note this is the struct called stat64 in Windows. Not stat, nor stati64.
57  | |     pub struct stat {
58  | |         pub st_dev: dev_t,
...   |
102 | |     }
103 | | }
    | |_- similarly named struct `sockaddr` defined here

error[E0412]: cannot find type `socklen_t` in crate `libc`
   --> src\net\raw_sockets.rs:102:62
    |
102 |                 mem::size_of::<libc::sockaddr_ll>() as libc::socklen_t,
    |                                                              ^^^^^^^^^ not found in `libc`

error[E0425]: cannot find function `recv` in crate `libc`
   --> src\net\raw_sockets.rs:114:29
    |
114 |             let len = libc::recv(
    |                             ^^^^ not found in `libc`

error[E0425]: cannot find function `send` in crate `libc`
   --> src\net\raw_sockets.rs:129:29
    |
129 |             let len = libc::send(
    |                             ^^^^ not found in `libc`

error[E0425]: cannot find value `AF_PACKET` in crate `libc`
   --> src\net\raw_sockets.rs:162:23
    |
162 |                 libc::AF_PACKET,
    |                       ^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `SOCK_RAW` in crate `libc`
   --> src\net\raw_sockets.rs:163:23
    |
163 |                 libc::SOCK_RAW | libc::SOCK_NONBLOCK,
    |                       ^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `SOCK_NONBLOCK` in crate `libc`
   --> src\net\raw_sockets.rs:163:40
    |
163 |                 libc::SOCK_RAW | libc::SOCK_NONBLOCK,
    |                                        ^^^^^^^^^^^^^ not found in `libc`

Some errors have detailed explanations: E0412, E0422, E0425, E0433.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `matscan` (lib) due to 17 previous errors

**Comment by mat-1** [comment]
matscan doesn't support Windows, WSL might work (I haven't tried it) but I recommend you use an actual Linux machine.
