### ISSUE TITLE
Question: how do you get around the Mojang rate limits?

### ISSUE THREAD

**Issue by HyperSkys** [mat-1/matscan#10]
When "Herobrine" tries to join and fails it seems like the "matscan" account attempts to join as well. I assume that matscan account gets limited by Mojang a lot, how do you get around that?

**Comment by mat-1** [comment]
The bot doesn't actually do any ratelimit bypassing; there's few enough servers that it has to join that it's acceptable to just wait a few seconds before every online-mode join for the ratelimit to not kick in.
