### ISSUE TITLE
Unneccessary amount of login requests (annoying).

### ISSUE THREAD

**Issue by Naamloos** [mat-1/matscan#11]
Hi. Your bot keeps trying to connect to my (whitelisted and online-mode) modded server. Even after failing once, it keeps and keeps on trying, filling my logs with login requests.

Can you please add either a blacklist, or some kind of feature to stop trying after a server is safe?

Thank you in advance.
![image](https://github.com/mat-1/matscan/assets/12187179/e7dc1dd7-5856-4aaa-81f9-575352d27b83)

**Comment by Naamloos** [comment]
Keeping this issue open for further clarification but I have fully blocked your IP from accessing my VPS whatsoever. Just so you know.

**Comment by mat-1** [comment]
Hi, that's not my scanner. My bot joins from the IP `151.115.73.107`.

**Comment by Naamloos** [comment]
that's.. interesting. Oh well. It's blocked.
