### ISSUE TITLE
Your Minecraft scanner came through randomly on my ngrok tcp tunnel

### ISSUE THREAD

**Issue by mastercodeon314** [mat-1/matscan#2]
I was running an ngrok tcp tunnel, and randomly I would assume your Minecraft server scanner came through my tunnel and dropped the link to your site as shown below. 
Why and how???
![IMG_20231231_153555_423](https://github.com/mat-1/matscan/assets/78676320/0c5c9682-2ee0-4d93-ae79-d820bb94ea60)

**Comment by mat-1** [comment]
Hi, my scanner searches for Minecraft servers by sending a [server list ping](https://wiki.vg/Server_List_Ping) packet to every* IP and port. The server list ping packet I send includes that string you see as the "server address" part (vanilla servers ignore it) so people watching their logs can find out who I am and see the scanner isn't malicious.

**Comment by k0mraid3** [comment]
> Hi, my scanner searches for Minecraft servers by sending a [server list ping](https://wiki.vg/Server_List_Ping) packet to every* IP and port and it randomly happened to ping your Ngrok IP and port. The server list ping packet I send includes that string you see as the "server address" part (vanilla servers ignore it) so people watching their logs can find out who I am and see the scanner isn't malicious.

Oh wow thanks for actually breaking that down for us. We are Security Researchers and found it intresting as it happened almost the second we popped it open. Good timing maybe? lol. 

I also appriciate you taking the time to add that bit to the server address bit, it makes our lives SO much easier when we can check and see its just someone working on one of their own legit projects! 

Thank you man, best wishes and keep on keepin' on! 

--K0mraid
